#############################################
# USERS TESTS
#############################################

### Get ALL users
GET http://localhost:7000/user
Content-Type: application/json

###

### Get ONE user by ID
GET http://localhost:7000/user/
Content-Type: application/json

###

### Create NEW user (no auth required for GET, but POST is protected)
POST http://localhost:7000/user
Content-Type: application/json

{
  "username": "testUser",
  "firstName": "Test",
  "lastName": "User",
  "email": "test@example.com",
  "age": 25
}

###

### UPDATE user
PUT http://localhost:7000/user/
Content-Type: application/json

{
  "firstName": "Updated",
  "lastName": "User",
  "email": "updated@example.com"
}

###

### DELETE user
DELETE http://localhost:7000/user/
Content-Type: application/json


#############################################
# FAVORITES TESTS
#############################################

### Get ALL favorites
GET http://localhost:7000/favorites
Content-Type: application/json

###

### Get ONE favorite
GET http://localhost:7000/favorites/
Content-Type: application/json

###

### Create favorite (requires OAuth)
POST http://localhost:7000/favorites
Content-Type: application/json

{
  "firstName": "Nely",
  "lastName": "Crespin",
  "favoriteFood": "Tacos",
  "favoriteColor": "Lavender",
  "favoriteSong": "Shallow",
  "favoriteMovie": "Moana",
  "favoriteHobby": "Decorating",
  "birthday": "1990-07-10"
}

###

### UPDATE favorite
PUT http://localhost:7000/favorites/
Content-Type: application/json

{
  "favoriteFood": "Tamales",
  "favoriteColor": "Purple"
}

###

### DELETE favorite
DELETE http://localhost:7000/favorites/
Content-Type: application/json


#############################################
# ACTIVITIES TESTS
#############################################

### Get ALL activities
GET http://localhost:7000/activities
Content-Type: application/json

###

### Get ONE activity
GET http://localhost:7000/activities/
Content-Type: application/json

###

### Create NEW activity (requires OAuth)
POST http://localhost:7000/activities
Content-Type: application/json

{
  "eventName": "Birthday Party",
  "eventDate": "2025-05-10",
  "location": "Provo",
  "description": "Family celebration"
}

###

### UPDATE activity
PUT http://localhost:7000/activities/
Content-Type: application/json

{
  "location": "Orem",
  "description": "Updated event description"
}

###

### DELETE activity
DELETE http://localhost:7000/activities/
Content-Type: application/json


#############################################
# REVIEWS TESTS
#############################################

### Get ALL reviews
GET http://localhost:7000/reviews
Content-Type: application/json

###

### Get ONE review
GET http://localhost:7000/reviews/
Content-Type: application/json

###

### Create review (requires OAuth)
POST http://localhost:7000/reviews
Content-Type: application/json

{
  "itemType": "movie",
  "itemName": "Encanto",
  "rating": 5,
  "comment": "Amazing movie!"
}

###

### UPDATE review
PUT http://localhost:7000/reviews/
Content-Type: application/json

{
  "rating": 4,
  "comment": "Updated comment"
}

###

### DELETE review
DELETE http://localhost:7000/reviews/
Content-Type: application/json
